In [1]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import random

# make results reproducible
np.random.seed(42)
random.seed(42)

print("Libraries loaded successfully!")

Libraries loaded successfully!

In [2]:
sources = [
    "Twitter",
    "Discord Invite",
    "Referral",
    "Event",
    "Ambassador Program"
]

countries = [
    "India",
    "USA",
    "UK",
    "Germany",
    "Singapore",
    "Canada",
    "Brazil",
    "Nigeria",
    "Philippines",
    "Australia"
]

print("Categories created successfully!")

Categories created successfully!

In [3]:
num_users = 5000

start_date = datetime(2024, 1, 1)
end_date = datetime(2025, 12, 31)

users = pd.DataFrame({
    "user_id": [f"U{i:04d}" for i in range(1, num_users + 1)],
    "join_date": [
        start_date + timedelta(
            days=random.randint(0, (end_date - start_date).days)
        )
        for _ in range(num_users)
    ],
    "source": np.random.choice(
        sources,
        size=num_users,
        p=[0.35, 0.20, 0.15, 0.15, 0.15]
    ),
    "country": np.random.choice(countries, size=num_users),
    "wallet_connected": np.random.choice(
        ["Yes", "No"],
        size=num_users,
        p=[0.7, 0.3]
    )
})

users.head()

  user_id  join_date              source  country wallet_connected
0   U0001 2025-10-16      Discord Invite       UK              Yes
1   U0002 2024-04-24  Ambassador Program  Nigeria              Yes
2   U0003 2024-01-26               Event   Brazil               No
3   U0004 2024-10-08            Referral       UK               No
4   U0005 2024-09-07             Twitter   Canada              Yes

In [4]:
users.shape

(5000, 5)

In [5]:
users.to_csv("../Data/users.csv", index=False)

print("users.csv saved successfully!")

users.csv saved successfully!

In [6]:
activity_types = [
    "Message",
    "AMA Join",
    "Event Join",
    "Quest Complete",
    "Referral"
]

print("Activity types created successfully!")

Activity types created successfully!

In [7]:
activities = []

print("Activity list created!")

Activity list created!

In [9]:
num_activities = 25000

for i in range(1, num_activities + 1):

    user = users.sample(1).iloc[0]

    activity_date = user["join_date"] + timedelta(
        days=random.randint(0, 180)
    )

    activities.append([
        f"A{i:05d}",
        user["user_id"],
        activity_date,
        random.choice(activity_types),
        random.randint(1, 50)
    ])

print("Activities generated successfully!")

Activities generated successfully!

In [10]:
activities_df = pd.DataFrame(
    activities,
    columns=[
        "activity_id",
        "user_id",
        "activity_date",
        "activity_type",
        "points_earned"
    ]
)

activities_df.head()

  activity_id user_id activity_date   activity_type  points_earned
0      A00001   U1446    2025-11-26  Quest Complete             37
1      A00002   U2065    2025-11-04         Message             32
2      A00003   U4711    2025-08-18      Event Join              8
3      A00004   U3983    2024-08-12         Message              7
4      A00005   U4493    2026-03-11  Quest Complete              3

In [11]:
activities_df.shape

(50000, 5)

In [12]:
activities_df.to_csv("../Data/activities.csv", index=False)

print("activities.csv saved successfully!")

activities.csv saved successfully!

In [13]:
campaign_names = [
    "Twitter Growth Campaign",
    "Airdrop Campaign",
    "Community Quest Program",
    "Referral Drive",
    "Ambassador Recruitment",
    "Discord Expansion",
    "Telegram Growth Push",
    "NFT Giveaway Campaign",
    "AMA Engagement Series",
    "Web3 Education Program",
    "Hackathon Promotion",
    "Partnership Awareness Campaign"
]

print("Campaign names created successfully!")

Campaign names created successfully!

In [14]:
campaigns = pd.DataFrame({
    "campaign_id": [f"C{i:03d}" for i in range(1, 13)],
    "campaign_name": campaign_names,
    "start_date": pd.date_range(
        start="2024-01-01",
        periods=12,
        freq="MS"
    ),
    "spend_usd": np.random.randint(
        2000,
        10000,
        size=12
    )
})

campaigns["end_date"] = campaigns["start_date"] + pd.Timedelta(days=29)

campaigns.head()

  campaign_id            campaign_name start_date  spend_usd   end_date
0        C001  Twitter Growth Campaign 2024-01-01       2377 2024-01-30
1        C002         Airdrop Campaign 2024-02-01       4480 2024-03-01
2        C003  Community Quest Program 2024-03-01       2010 2024-03-30
3        C004           Referral Drive 2024-04-01       8756 2024-04-30
4        C005   Ambassador Recruitment 2024-05-01       2577 2024-05-30

In [15]:
campaigns.to_csv("../Data/campaigns.csv", index=False)

print("campaigns.csv saved successfully!")

campaigns.csv saved successfully!

In [16]:
user_campaigns = pd.DataFrame({
    "user_id": np.random.choice(
        users["user_id"],
        size=5000,
        replace=False
    ),
    "campaign_id": np.random.choice(
        campaigns["campaign_id"],
        size=5000
    )
})

user_campaigns.head()

  user_id campaign_id
0   U1240        C005
1   U2551        C008
2   U3372        C004
3   U4130        C008
4   U1559        C010

In [17]:
user_campaigns.to_csv("../Data/user_campaigns.csv", index=False)

print("user_campaigns.csv saved successfully!")

user_campaigns.csv saved successfully!